### ISSUE TITLE
yarn create bolt-cep fails

### ISSUE THREAD

**Issue by apohl79** [hyperbrew/bolt-cep#62]
I can't create a new project via

`yarn create bolt-cep ceptest -t skeleton -f react -a ppro -p com.ceptest.cep -n CEPTest`

Getting the following error output:

```
┌   create-bolt-cep
│   by Hyper Brew | https://hyperbrew.co
│
◇  Inputs ─────────────────────────────────────────────────────────────────╮
│                                                                          │
│  panel      ceptest (CEPTest)                                            │
│  id         com.ceptest.cep                                              │
│  framework  React                                                        │
│  template   Skeleton (only selected apps and no sample UI or functions)  │
│  apps       Premiere Pro                                                 │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
│
○  Installing bolt-cep
/private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:1853
  return Object.assign(new Error(`${code}: ${message}`), { code });
                       ^

Error: ENOENT: no such file or directory, lstat '/node_modules/bolt-cep'
    at makeError$1 (/private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:1853:24)
    at ENOENT (/private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:1868:10)
    at ZipFS.lstatSync (/private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:3325:13)
    at /private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:4624:20
    at /private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:5046:60
    at ZipOpenFS.getZipSync (/private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:5175:14)
    at ZipOpenFS.makeCallSync (/private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:5046:17)
    at ZipOpenFS.lstatSync (/private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:4621:17)
    at VirtualFS.lstatSync (/private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:4073:24)
    at PosixFS.lstatSync (/private/var/folders/bc/rqk94w6s5gvg1hfcwfr6y9rw0000gn/T/xfs-afe1ee1a/dlx-75288/.pnp.cjs:4073:24) {
  code: 'ENOENT'
}

Node.js v18.15.0
``` 

I'm on macOS 13.2.1 on an Intel Mac.

Thanks a lot!

**Comment by apohl79** [comment]
Thx a mill for the quick a reply and solution! That worked!

**Comment by justintaylor-dev** [comment]
Awesome!
