### ISSUE TITLE
Failed to create a symlink on Windows machine

### ISSUE THREAD

**Issue by avibiton13** [hyperbrew/bolt-cep#78]
Environment - Windows 11 Pro (Version 10.0.22621 Build 22621, Intel i7-9700).

Following the instruction in this repo `README.md` file, when running `yarn build` I get the following error:
`symlink failed. Try running 'sudo yarn symlink' → failed ×`, and obviously when launching the targeted adobe product(which is After Effects in my case) - I cannot open my CEP extension.

Trying to run `yarn build` using administrator account doesn't help, regardless of the terminal program in use(`cmd.exe`/`PowerShell`/`Git Bash`).

I did manage to bypass that issue using this workaround:
- Launching Windows Command Prompt as administrator.
- Executing this command: `mklink /D "C:\Program Files\Common Files\Adobe\CEP\extensions\<my-panel-id>" "<path-to-my-bolt-app-root-source-code-folder>\dist\cep"`

With that my CEP app is visible in After Effects *Extension* menu, and I can interact with it perfectly.

Please consider a fix for that issue, so we won't have to use that bandage I've mentioned above.

**Comment by justintaylor-dev** [comment]
Is this on a new Bolt install? Is your user an Admin? Perhaps try updating the plugin `yarn add vite-cep-plugin`

**Comment by justintaylor-dev** [comment]
Haven't had any other Windows users report this issue. If it comes up again feel free to re-open and provide additional details.

**Comment by avibiton13** [comment]
@justintaylor-dev updating the vite cep plugin by running `yarn add vite-cep-plugin` resolved the issue!

**Comment by justintaylor-dev** [comment]
awesome!

**Comment by Jalan-Ember-SN** [comment]
Hi! I was having this issue and tried running `yarn add vite-cep-plugin` and then `yarn build` again. However it failed with the following error:
```
failed to load config from C:\[...]\vite.config.ts
error during build:
TypeError: Cannot destructure property 'iife' of 'undefined' as it is undefined.
    at jsxInclude (C:\[project folder]\node_modules\vite-cep-plugin\lib\index.js:338:23)
    at extendscriptConfig (C:\[project folder]\vite.config.ts:142:45)   
    at Object.<anonymous> (C:\[project folder]\vite.config.ts:233:1)    
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at require.extensions.<computed> [as .ts] (C:\[project folder]\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:62006:20)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadConfigFromBundledFile (C:\[project folder]\node_modules\vite\dist\node\chunks\dep-6e2fe41e.js:62014:17)
error Command failed with exit code 1.
```
I am not sure what to make of this. Any thoughts appreciated!

**Comment by tinogithub** [comment]
I am encountering this problem after cloning my repository to another machine. Both windows.
I launched:
1. yarn (install all dependencies)
2. yarn build

There I get the error. Tried as user and administrator.

```
manifest created → succeeded √  
debug file created → succeeded √
Error: EINVAL: invalid argument, readlink 'C:\Users\***\AppData\Roaming\Adobe\CEP\extensions\com.***.***.cep'
    at Object.readlinkSync (node:fs:1703:18)
    at makeSymlink (D:\***\node_modules\vite-cep-plugin\lib\index.js:41:33)
    at Object.<anonymous> (D:\***\node_modules\vite-cep-plugin\lib\index.js:328:33)
    at Generator.next (<anonymous>)
    at D:\***\node_modules\vite-cep-plugin\lib\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\***\node_modules\vite-cep-plugin\lib\index.js:4:12)
    at Object.generateBundle (D:\***\node_modules\vite-cep-plugin\lib\index.js:254:20)
    at file:///D:/***/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25544:40 {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'readlink',
  path: 'C:\\Users\\***\\AppData\\Roaming\\Adobe\\CEP\\extensions\\com.***.***.cep'
}
symlink failed. Try running 'sudo yarn symlink' → failed ×  
undefined
```

"yarn add vite-cep-plugin" didn't help.
